- name: Check if ansible can list this local directory in WSL bash
  hosts: localhost
  tasks:
    - name: 🚧 PTest cmd.exe for operations
      ansible.builtin.shell: |
        dir
      changed_when: false
      register: result_cmd
      args:
        executable: "/mnt/c/WINDOWS/system32/cmd.exe"
    - name: 🚧 Prepair pwsh for operations
      ansible.builtin.raw: |
        Install-Module powershell-yaml -AcceptLicense -force
      changed_when: false
      args:
        executable: "$LOCALAPPDATA/Microsoft/WindowsApps/pwsh.exe -nologo"
    - name: 🚧 List files in current directory
      ansible.builtin.raw: |
        $PSStyle.OutputRendering = 'PlainText'
        get-vm Srv-021_3CX | select State | ConvertTo-Yaml
      register: result
      changed_when: false
      args:
        executable: "$LOCALAPPDATA/Microsoft/WindowsApps/pwsh.exe -nologo"
    - name: 🖨️ Print result
      when: result.stdout_lines[0]
      ansible.builtin.debug:
        var: result.stdout_lines[0]
    - name: 🖨️ Print result2
      when: result_cmd
      ansible.builtin.debug:
        var: result_cmd
    - name: 🖨️ Print error
      when: result.stderr
      ansible.builtin.debug:
        var: result.stderr
